---
openapi: 3.0.0
info:
  title: Swagger Hotelbook
  description: |
    This is a Hotelbook server API.
  contact:
    email: ilian@star.global
  version: 1.0.0-oas3
servers:
  - url: https://hotel-booking-server-api.herokuapp.com/
tags:
  - name: test
    description: Test routes
  - name: user
    description: User data
  - name: hotel
    description: Hotel data
paths:
  /:
    get:
      tags:
        - test
      summary: Test connection
      responses:
        "200":
          description: Hello World
  /api/v1/user:
    get:
      tags:
        - user
      summary: All users list
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /api/v1/user/signup:
    post:
      tags:
        - user
      summary: Sign up a new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistration'
            example:
              name: John
              email: jonh@gmail.com
              password: qwerty
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        "400":
          description: user already exists
  /api/v1/user/login:
    post:
      tags:
        - user
      summary: Login a user to get a JWT token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserAuthorization'
            example:
              email: jonh@gmail.com
              password: qwerty
      responses:
        "200":
          description: successful operation
          headers:
            Jwt-Authorization:
              description: A token for subsequent requests
              style: simple
              explode: false
              schema:
                type: string
        "404":
          description: there is no user with this email and password
  /hotel:
    get:
      tags:
        - hotel
      summary: All hotels
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Hotel'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
    Hotel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        country:
          type: string
        city:
          type: string
      xml:
        name: Hotel
    UserRegistration:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
    UserAuthorization:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
