---
openapi: 3.0.0
info:
  title: Swagger Hotelbook
  description: |
    This is a Hotelbook server API.
  contact:
    email: ilian@star.global
  version: 1.0.0-oas3
servers:
  - url: /
tags:
  - name: test
    description: Test routes
  - name: user
    description: User data
  - name: hotel
    description: Hotel data
paths:
  /:
    get:
      tags:
        - test
      summary: Test connection
      responses:
        "200":
          description: Hello World
  /user:
    get:
      tags:
        - user
      summary: All users list
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /hotel:
    get:
      tags:
        - hotel
      summary: All hotels
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Hotel'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
    Hotel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        country:
          type: string
        city:
          type: string
      xml:
        name: User
